### ISSUE TITLE
Cannot get information from server which have use port 19132

### ISSUE THREAD

**Issue by sinhpn92** [lucaazalim/minecraft-server-ping#2]
Hi lucaazalim,
I did try to use this lib to fetch server infor of `bw.lbsg.net:19132`. But I have got error this server not online.
What's wrong here?

**Comment by Pequla** [comment]
Bedrock Edition servers don't use the same protocol as Java Edition servers. For bedrock edition so far i have not seen a single lib available.

This lib only works for java edition servers
