### ISSUE TITLE
Still functional?

### ISSUE THREAD

**Issue by QuenK30** [lucaazalim/minecraft-server-ping#4]
Hello ! I was wondering if this was still working? I wanted to test but I have the impression that some class is missing lines

good day

**Comment by rtm516** [comment]
It is.
See https://github.com/GeyserMC/GeyserDiscordBot/blob/master/src/main/java/org/geysermc/discordbot/commands/PingCommand.java#L111-L121

**Comment by lucaazalim** [comment]
@QuenK30 yes, it should be working just fine. Feel free to open a new issue if you find any problems with it.
