### ISSUE TITLE
Incorrect answer and errors

### ISSUE THREAD

**Issue by ServOKio** [lucaazalim/minecraft-server-ping#7]
Responds that the servers are unavailable while they are working
1. `nicegrief.ml`
2. `mc.nekocloud.me`

+ error when getting the description on `PLAY.ORIGINREALMS.COM`

**Comment by lucaazalim** [comment]
Hello! Thank you for your issue.

`nicegrief.ml` and `mc.nekocloud.me` seem to be down.

- https://mcsrvstat.us/server/nicegrief.ml
- https://mcsrvstat.us/server/mc.nekocloud.me

I was able to get the description of `play.originrealms.com`. Take a look at the `MCPingExample` class output:

```
Full response from PLAY.ORIGINREALMS.COM:

Description:
    Raw: §f§f§f§f            §x§3§8§b§d§f§8§lOrigin Realms§x§d§1§d§8§e§2 - §x§f§b§b§f§2§3§lBeta 0.21.2
§x§f§b§b§f§2§3              §x§f§f§f§3§7§3Begin Your Adventure Today
    No color codes:             Origin Realms - Beta 0.21.2
              Begin Your Adventure Today

Players: 
    Online count: 263
    Max players: 800

...
```
